"use client";

import { useEffect, useState } from "react";
import { Activity, CheckCircle2, ChevronRight, ClipboardList, Trash2 } from "lucide-react";
import { useI18n } from "@/components/i18n-provider";
import { platformApiMessage, platformApiRequest } from "@/lib/platform-api";
import type { PlatformAdminPreprodCleanupResult, PlatformAdminPreprodTestRun, PlatformUser } from "@/lib/platform-types";

export function AdminPreprodPage({ runs, currentUser, formatDate, onReload }: { runs: PlatformAdminPreprodTestRun[]; currentUser: PlatformUser; formatDate: (value: string) => string; onReload: () => Promise<void> }) {
  const { t } = useI18n(); const [selectedMarker, setSelectedMarker] = useState<string | null>(runs[0]?.marker ?? null); const [confirm, setConfirm] = useState(""); const [note, setNote] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const selected = runs.find((run) => run.marker === selectedMarker) ?? runs[0] ?? null; const isSuperadmin = currentUser.roles.includes("superadmin"); const canClean = isSuperadmin && confirm === "DELETE_TEST_DATA" && note.trim().length >= 3 && !busy;
  useEffect(() => { if (!selectedMarker || !runs.some((run) => run.marker === selectedMarker)) setSelectedMarker(runs[0]?.marker ?? null); }, [runs, selectedMarker]);
  async function clean(all: boolean) { if (!canClean || (!all && !selected)) return; setBusy(true); setError(""); setMessage(""); try { const path = all ? "/admin/preprod-test-runs/cleanup" : `/admin/preprod-test-runs/${encodeURIComponent(selected!.marker)}/cleanup`; const result = await platformApiRequest<PlatformAdminPreprodCleanupResult>(path, { method: "POST", body: JSON.stringify({ confirm, note: note.trim() }) }); setMessage(t("admin.new.preprodCleanupDone", { users: result.users_deleted, tournaments: result.tournaments_deleted })); setConfirm(""); setNote(""); try { await onReload(); } catch { /* Cleanup is already committed; keep the success state visible. */ } } catch (requestError) { setError(platformApiMessage(requestError, t("admin.new.preprodCleanupFailed"))); } finally { setBusy(false); } }
  return <section className="ops-page" data-testid="admin-preprod-page"><div className="ops-page-title-row"><div><span className="ops-kicker">{t("admin.new.preprod")}</span><h1>{t("admin.new.preprodTitle")}</h1><p>{t("admin.new.preprodCopy")}</p></div><div className="ops-page-count"><strong>{runs.length.toLocaleString("ru-RU")}</strong><span>{t("admin.new.preprodCount")}</span></div></div><div className="ops-info ops-info-wide"><Activity size={17} /><span>{t("admin.new.preprodNotice")}</span></div><div className="ops-list-detail"><section className="ops-panel ops-list-panel"><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>{t("admin.new.marker")}</th><th>{t("admin.new.state")}</th><th>{t("admin.new.generatedUsers")}</th><th>{t("admin.new.generatedTournaments")}</th><th>{t("admin.new.matches")}</th><th>{t("admin.new.time")}</th></tr></thead><tbody>{runs.map((run) => <tr className={selected?.marker === run.marker ? "is-selected" : ""} data-testid={`admin-preprod-run-${run.marker}`} key={run.marker} tabIndex={0} onClick={() => setSelectedMarker(run.marker)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelectedMarker(run.marker); } }}><td><strong>{run.marker}</strong><small className="ops-table-subtext">{run.origin ?? "—"}</small></td><td><span className={`ops-status ops-status-${preprodTone(run.status)}`}>{preprodLabel(run.status, t)}</span></td><td>{run.created_users}/{run.requested_users}</td><td>{run.tournaments_created}</td><td>{run.matches_count}</td><td className="ops-table-date">{formatDate(run.started_at ?? run.created_at)}</td><td><ChevronRight size={16} /></td></tr>)}</tbody></table></div>{!runs.length ? <div className="ops-empty-inline"><Activity size={18} /><span>{t("admin.new.preprodEmpty")}</span></div> : null}</section><PreprodDetail run={selected} currentUser={currentUser} confirm={confirm} note={note} busy={busy} message={message} error={error} onConfirm={setConfirm} onNote={setNote} onClean={clean} /></div></section>;
}

function PreprodDetail({ run, currentUser, confirm, note, busy, message, error, onConfirm, onNote, onClean }: { run: PlatformAdminPreprodTestRun | null; currentUser: PlatformUser; confirm: string; note: string; busy: boolean; message: string; error: string; onConfirm: (value: string) => void; onNote: (value: string) => void; onClean: (all: boolean) => void }) {
  const { t } = useI18n(); const isSuperadmin = currentUser.roles.includes("superadmin");
  return <aside className="ops-detail" data-testid="admin-preprod-inspector">{run ? <><div className="ops-detail-header"><div><span className="ops-kicker">{t("admin.new.preprodRun")}</span><h2>{run.marker}</h2><p>{run.finished_at ? t("admin.new.finishedAt", { value: new Date(run.finished_at).toLocaleString("ru-RU") }) : t("admin.new.running")}</p></div><span className={`ops-status ops-status-${preprodTone(run.status)}`}>{preprodLabel(run.status, t)}</span></div><div className="ops-fact-grid"><Fact label={t("admin.new.generatedUsers")} value={String(run.created_users)} /><Fact label={t("admin.new.activeParticipants")} value={String(run.active_participants)} /><Fact label={t("admin.new.teams")} value={String(run.teams_count)} /><Fact label={t("admin.new.matches")} value={String(run.matches_count)} /></div>{run.report_path ? <div className="ops-info"><ClipboardList size={15} /><span>{run.report_path}</span></div> : null}{run.cleanup_state?.ok ? <div className="ops-info"><CheckCircle2 size={15} /><span>{t("admin.new.alreadyCleaned")}</span></div> : null}</> : <div className="ops-detail-empty"><Activity size={22} /><strong>{t("admin.new.selectPreprodTitle")}</strong><span>{t("admin.new.selectPreprodCopy")}</span></div>}<details className="ops-danger-zone"><summary><Trash2 size={15} />{t("admin.new.preprodCleanupTitle")}</summary><div className="ops-danger-content"><p>{isSuperadmin ? t("admin.new.preprodCleanupCopy") : t("admin.new.superadminOnly")}</p><label className="ops-field"><span>{t("admin.new.preprodConfirm")}</span><input data-testid="admin-preprod-cleanup-confirm" disabled={!isSuperadmin} maxLength={16} value={confirm} onChange={(event) => onConfirm(event.target.value)} /></label><label className="ops-field"><span>{t("admin.new.reason")}</span><textarea value={note} maxLength={1000} onChange={(event) => onNote(event.target.value)} /></label>{message ? <div className="ops-feedback ops-feedback-success">{message}</div> : null}{error ? <div className="ops-feedback ops-feedback-error">{error}</div> : null}<div className="ops-action-column"><button className="ops-button ops-button-danger" data-testid="admin-preprod-cleanup-selected" type="button" disabled={!run || !isSuperadmin || confirm !== "DELETE_TEST_DATA" || note.trim().length < 3 || busy} onClick={() => onClean(false)}><Trash2 size={15} />{t("admin.new.cleanSelected")}</button><button className="ops-button ops-button-danger" data-testid="admin-preprod-cleanup-all" type="button" disabled={!runsAvailable(run) || !isSuperadmin || confirm !== "DELETE_TEST_DATA" || note.trim().length < 3 || busy} onClick={() => onClean(true)}><Trash2 size={15} />{t("admin.new.cleanAll")}</button></div></div></details></aside>;
}

function runsAvailable(run: PlatformAdminPreprodTestRun | null): boolean { return Boolean(run); }
function Fact({ label, value }: { label: string; value: string }) { return <div className="ops-fact"><span>{label}</span><strong>{value}</strong></div>; }
function preprodTone(status: string): string { return status === "passed" || status === "cleaned" ? "success" : status === "failed" ? "danger" : "info"; }
function preprodLabel(status: string, t: (key: string) => string): string { return ({ running: t("admin.new.preprodRunning"), passed: t("admin.new.preprodPassed"), failed: t("admin.new.preprodFailed"), cleaned: t("admin.new.preprodCleaned") } as Record<string, string>)[status] ?? status; }
