"use client";

import { useMemo, useState } from "react";
import { ClipboardList, Search, ShieldCheck } from "lucide-react";
import { useI18n } from "@/components/i18n-provider";
import type { PlatformAuditLog } from "@/lib/platform-types";

export function AdminAuditPage({ auditLogs, selectedAuditId, formatDate, onSelect }: { auditLogs: PlatformAuditLog[]; selectedAuditId: number | null; formatDate: (value: string) => string; onSelect: (id: number) => void }) {
  const { t } = useI18n(); const [search, setSearch] = useState(""); const normalized = search.trim().toLowerCase();
  const filtered = useMemo(() => auditLogs.filter((audit) => !normalized || [audit.action, audit.subject_type, audit.subject_id ?? "", audit.actor_display_name ?? "", audit.actor_email ?? "", String(audit.payload.note ?? "")].join(" ").toLowerCase().includes(normalized)), [auditLogs, normalized]);
  const selected = auditLogs.find((audit) => audit.id === selectedAuditId) ?? null;
  return <section className="ops-page" data-testid="admin-audit-page"><div className="ops-page-title-row"><div><span className="ops-kicker">{t("admin.new.audit")}</span><h1>{t("admin.new.auditTitle")}</h1><p>{t("admin.new.auditCopy")}</p></div><div className="ops-page-count"><strong>{auditLogs.length.toLocaleString("ru-RU")}</strong><span>{t("admin.new.auditCount")}</span></div></div><div className="ops-toolbar"><label className="ops-search"><Search size={17} /><input maxLength={120} value={search} placeholder={t("admin.new.auditSearchPlaceholder")} onChange={(event) => setSearch(event.target.value)} /></label><span className="ops-toolbar-count">{t("admin.new.shownOf", { shown: filtered.length, total: auditLogs.length })}</span></div><div className="ops-list-detail"><section className="ops-panel ops-list-panel"><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>{t("admin.new.time")}</th><th>{t("admin.new.actor")}</th><th>{t("admin.new.action")}</th><th>{t("admin.new.resource")}</th><th>{t("admin.new.reason")}</th></tr></thead><tbody>{filtered.map((audit) => <tr className={selected?.id === audit.id ? "is-selected" : ""} key={audit.id} tabIndex={0} onClick={() => onSelect(audit.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelect(audit.id); } }}><td className="ops-table-date">{formatDate(audit.created_at)}</td><td><strong>{audit.actor_display_name ?? t("admin.new.systemActor")}</strong><small className="ops-table-subtext">{audit.actor_email ?? "—"}</small></td><td><code className="ops-code">{audit.action}</code></td><td><strong>{audit.subject_type}</strong><small className="ops-table-subtext">{audit.subject_id ?? "—"}</small></td><td className="ops-truncate-cell">{String(audit.payload.note ?? "—")}</td></tr>)}</tbody></table></div>{!filtered.length ? <div className="ops-empty-inline"><ClipboardList size={18} /><span>{t("admin.new.noAudit")}</span></div> : null}</section><AuditDetail audit={selected} formatDate={formatDate} /></div></section>;
}

function AuditDetail({ audit, formatDate }: { audit: PlatformAuditLog | null; formatDate: (value: string) => string }) {
  const { t } = useI18n();
  if (!audit) return <aside className="ops-detail ops-detail-empty"><ClipboardList size={22} /><strong>{t("admin.new.selectAuditTitle")}</strong><span>{t("admin.new.selectAuditCopy")}</span></aside>;
  return <aside className="ops-detail" data-testid="admin-audit-inspector"><div className="ops-detail-header"><div><span className="ops-kicker">{t("admin.new.auditEvent")}</span><h2>{audit.action}</h2><p>{formatDate(audit.created_at)}</p></div><span className="ops-detail-mark"><ShieldCheck size={18} /></span></div><div className="ops-detail-facts"><Fact label={t("admin.new.actor")} value={audit.actor_display_name ?? t("admin.new.systemActor")} /><Fact label={t("admin.new.resource")} value={audit.subject_type} /><Fact label={t("admin.new.resourceId")} value={audit.subject_id ?? "—"} /></div><div className="ops-detail-section"><div className="ops-section-title"><h3>{t("admin.new.reason")}</h3><p>{String(audit.payload.note ?? t("admin.new.noReason"))}</p></div></div><div className="ops-detail-section"><div className="ops-section-title"><h3>{t("admin.new.rawPayload")}</h3><p>{t("admin.new.rawPayloadCopy")}</p></div><pre className="ops-json">{JSON.stringify(audit.payload, null, 2)}</pre></div></aside>;
}

function Fact({ label, value }: { label: string; value: string }) { return <div className="ops-fact"><span>{label}</span><strong>{value}</strong></div>; }
